# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Projeto_Pock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Projeto_Pock
	pod 'Tanjiro'
  	pod "PromiseKit", "~> 6.8"
end
